"""Add fields to Vac

Revision ID: 04c310f7585f
Revises: fa0193841fde
Create Date: 2026-07-17 10:30:08.574927

"""


from alembic import op
import sqlalchemy as sa

revision: str = '04c310f7585f'
down_revision: str | None = 'fa0193841fde'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('embedding_text', sa.Text(), nullable=True))
    op.add_column('vacancies', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('vacancies', sa.Column('nice_to_have', sa.Text(), nullable=True))
    op.add_column('vacancies', sa.Column('experience', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('seniority', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'seniority')
    op.drop_column('vacancies', 'experience')
    op.drop_column('vacancies', 'nice_to_have')
    op.drop_column('vacancies', 'requirements')
    op.drop_column('vacancies', 'embedding_text')
    # ### end Alembic commands ###