"""query_text are mullable in UserProfile

Revision ID: 2b801dd03393
Revises: e4a8b1c2d3f4
Create Date: 2026-07-05 13:43:05.954677

"""


from alembic import op
import sqlalchemy as sa

revision: str = '2b801dd03393'
down_revision: str | None = 'e4a8b1c2d3f4'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'query_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'query_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
