"""MatcherState updated_at:timezone=True

Revision ID: 46cdc0645ec3
Revises: 74234252195e
Create Date: 2026-07-29 15:53:18.022682

"""
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

revision: str = '46cdc0645ec3'
down_revision: str | None = '74234252195e'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matcher_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matcher_state', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
