"""cv_file, mime_type added

Revision ID: 740b0c40032f
Revises: 46cdc0645ec3
Create Date: 2026-08-04 09:02:40.443077

"""


from alembic import op
import sqlalchemy as sa

revision: str = '740b0c40032f'
down_revision: str | None = '46cdc0645ec3'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('cv_file', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('mime_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'mime_type')
    op.drop_column('user_profiles', 'cv_file')
    # ### end Alembic commands ###
