"""last_seen_at, addet_at, last_matchet_at timezone=true

Revision ID: 74234252195e
Revises: 8c02e9539aba
Create Date: 2026-07-27 15:14:42.504243

"""
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

revision: str = '74234252195e'
down_revision: str | None = '8c02e9539aba'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'last_matched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("'1970-01-01 00:00:00'::timestamp without time zone"))
    op.alter_column('vacancies', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vacancies', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'last_seen_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vacancies', 'added_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_profiles', 'last_matched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'1970-01-01 00:00:00'::timestamp without time zone"))
    # ### end Alembic commands ###
