"""add embedding column to vacancies and UserProfile

Revision ID: 79402d387bb8
Revises: ff40b567dad5
Create Date: 2026-07-13 09:00:59.301423

"""
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa

revision: str = '79402d387bb8'
down_revision: str | None = 'ff40b567dad5'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('user_profiles', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('user_profiles', sa.Column('embedding_model', sa.Text(), nullable=True))
    op.add_column('vacancies', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('vacancies', sa.Column('embedding_model', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'embedding_model')
    op.drop_column('vacancies', 'embedding')
    op.drop_column('user_profiles', 'embedding_model')
    op.drop_column('user_profiles', 'embedding')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
