"""Drop MatcherState

Revision ID: 83724a0cd9a7
Revises: cd00ae2fc817
Create Date: 2026-07-15 07:53:12.287142

"""
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

revision: str = '83724a0cd9a7'
down_revision: str | None = 'cd00ae2fc817'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matcher_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matcher_state',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('matcher_state_pkey'))
    )
    # ### end Alembic commands ###
