"""add stack, reason, confidence

Revision ID: 8c02e9539aba
Revises: 04c310f7585f
Create Date: 2026-07-27 10:34:32.191357

"""


from alembic import op
import sqlalchemy as sa

revision: str = '8c02e9539aba'
down_revision: str | None = '04c310f7585f'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_matches', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('user_matches', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('stack', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'stack')
    op.drop_column('user_matches', 'confidence')
    op.drop_column('user_matches', 'reason')
    # ### end Alembic commands ###
