"""add last_matched_at remove keyword_coverage

Revision ID: cd00ae2fc817
Revises: 79402d387bb8
Create Date: 2026-07-14 13:10:22.476090

"""
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

revision: str = 'cd00ae2fc817'
down_revision: str | None = '79402d387bb8'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_matches', 'semantic_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('user_matches', 'combined_score')
    op.drop_column('user_matches', 'keyword_coverage')
    op.drop_column('user_matches', 'reason_json')
    op.add_column('user_profiles', sa.Column('last_matched_at', sa.DateTime(), server_default=sa.text("'1970-01-01 00:00:00'"), nullable=False))
    op.drop_column('user_profiles', 'min_keyword_coverage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('min_keyword_coverage', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.2'), autoincrement=False, nullable=False))
    op.drop_column('user_profiles', 'last_matched_at')
    op.add_column('user_matches', sa.Column('reason_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_matches', sa.Column('keyword_coverage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('user_matches', sa.Column('combined_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('user_matches', 'semantic_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
