"""add Vacancy.last_seen_at

Revision ID: df5cf8a6f982
Revises: 83724a0cd9a7
Create Date: 2026-07-15 07:57:07.149619

"""


from alembic import op
import sqlalchemy as sa

revision: str = 'df5cf8a6f982'
down_revision: str | None = '83724a0cd9a7'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'last_seen_at')
    # ### end Alembic commands ###
