"""Add fields to Vac

Revision ID: eed1640ddd41
Revises: fa0193841fde
Create Date: 2026-07-17 09:49:20.984253

"""
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

revision: str = 'eed1640ddd41'
down_revision: str | None = 'fa0193841fde'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('N', 'J', 'SJ', 'M', 'S', name='seniorityenum').create(op.get_bind())
    op.add_column('vacancies', sa.Column('embedding_text', sa.Text(), nullable=True))
    op.add_column('vacancies', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('vacancies', sa.Column('nice_to_have', sa.Text(), nullable=True))
    op.add_column('vacancies', sa.Column('experience', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('seniority', postgresql.ENUM('N', 'J', 'SJ', 'M', 'S', name='seniorityenum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'seniority')
    op.drop_column('vacancies', 'experience')
    op.drop_column('vacancies', 'nice_to_have')
    op.drop_column('vacancies', 'requirements')
    op.drop_column('vacancies', 'embedding_text')
    sa.Enum('N', 'J', 'SJ', 'M', 'S', name='seniorityenum').drop(op.get_bind())
    # ### end Alembic commands ###
