"""add MatcherState

Revision ID: fa0193841fde
Revises: df5cf8a6f982
Create Date: 2026-07-15 09:18:34.348260

"""


from alembic import op
import sqlalchemy as sa

revision: str = 'fa0193841fde'
down_revision: str | None = 'df5cf8a6f982'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matcher_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='only_one_row_constraint'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matcher_state')
    # ### end Alembic commands ###
