"""remove content_hash from Vacancy, remove top_k from UserProfile

Revision ID: ff40b567dad5
Revises: 2b801dd03393
Create Date: 2026-07-12 10:36:11.364598

"""


from alembic import op
import sqlalchemy as sa

revision: str = 'ff40b567dad5'
down_revision: str | None = '2b801dd03393'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'top_k')
    op.drop_column('vacancies', 'content_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('content_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('top_k', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
