name: Run Filter Only

on:
  workflow_dispatch:

jobs:
  filter_only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code (Код успішно завантажено на сервер)
        uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run matching
        run: uv run run.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AI_MODEL_NAME: ${{ secrets.AI_MODEL_NAME }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
          RUN_MODE: "filter"
